apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260512-014615-1d56ysi0jgek-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260512-014615-1d56ysi0jgek.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260512-014615-1d56ysi0jgek-service
            port:
              number: 80
