apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260512-014615-1d56ysi0jgek-service
spec:
  selector:
    app: enterprise-system-20260512-014615-1d56ysi0jgek
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
